name: firebase_listener
description: Um script Dart puro para ouvir leituras do Firebase Firestore.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mysql1: ^0.20.0
  intl: ^0.19.0
  gcloud: ^0.8.11
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.6
